src/main/webapp/WEB-INF/views/common/commonlist.jsp
=> 민하 : commonlist 작성

src/main/java/com/laonworks502/team1st/controller/board/BoardController.java, src/main/java/com/laonworks502/team1st/service/board/BoardServiceImpl.java, src/main/webapp/WEB-INF/views/board/boardlist.jsp
=> board controller 수정

src/main/java/com/laonworks502/team1st/Config.java, src/main/java/com/laonworks502/team1st/controller/board/BoardController.java, src/main/java/com/laonworks502/team1st/interceptor/LoginInterceptor.java
BoardController 수정 : 변수 명명규칙 준수
인터셉터 구현 완료 : 임시로 막아두기 위해 config.java와 LoginInterceptor.java 주석 처리
=> BoardController 수정, 인터셉터 구현 : 태원

pom.xml, src/main/java/com/laonworks502/team1st/controller/users/GeneralUserController.java, src/main/java/com/laonworks502/team1st/dao/users/GeneralUserDao.java, src/main/java/com/laonworks502/team1st/service/users/GeneralUserServiceImpl.java, src/main/resources/application.properties, src/main/resources/static/mapper/users/GeneralUserMapper.xml, src/main/webapp/WEB-INF/views/generaluser/generaluserdelete.jsp, src/main/webapp/WEB-INF/views/generaluser/generaluseredit.jsp, src/main/webapp/WEB-INF/views/generaluser/generaluserinsert.jsp, src/main/webapp/WEB-INF/views/generaluser/loginForm.jsp, src/main/webapp/WEB-INF/views/generaluser/loginResult.jsp, src/main/webapp/WEB-INF/views/generaluser/loginselect.jsp, src/main/webapp/WEB-INF/views/generaluser/loginsuccess.jsp, src/main/webapp/WEB-INF/views/generaluser/pwfind.jsp, src/main/webapp/WEB-INF/views/generaluser/pwresult.jsp, src/main/webapp/WEB-INF/views/generaluser/resumeupload_ok.jsp
=> 업로드 구현 - 김철

src/main/java/com/laonworks502/team1st/controller/board/BoardController.java, src/main/webapp/WEB-INF/views/board/boardlist.jsp
=> boardlist 수정, 글 작성 session 연동

src/main/java/com/laonworks502/team1st/controller/board/BoardController.java, src/main/java/com/laonworks502/team1st/model/board/Pagination.java
=> Board Pagination 수정

src/main/java/com/laonworks502/team1st/controller/board/BoardController.java, src/main/java/com/laonworks502/team1st/dao/board/BoardDao.java, src/main/java/com/laonworks502/team1st/model/post/PostBean.java, src/main/java/com/laonworks502/team1st/service/board/BoardService.java, src/main/java/com/laonworks502/team1st/service/board/BoardServiceImpl.java, src/main/resources/application.properties, src/main/webapp/WEB-INF/views/board/posteditform.jsp, src/main/webapp/WEB-INF/views/board/postview.jsp
=> 글 수정 삭제 ajax 사용 완성 - 미강

src/main/java/com/laonworks502/team1st/controller/admin/AdminController.java, src/main/java/com/laonworks502/team1st/service/admin/AdminServiceImpl.java, src/main/resources/static/mapper/admin/AdminMapper.xml
AdminController, AdminServiceImpl, AdminMapper.xml 수정
=> AdminController, AdminServiceImpl, AdminMapper.xml 수정

src/main/resources/static/js/checkgeneral.js, src/main/webapp/WEB-INF/views/generaluser/generaluserinsert.jsp
=> 중복이메일 구분 완료 - 김철

src/main/java/com/laonworks502/team1st/controller/users/GeneralUserController.java, src/main/resources/static/mapper/users/GeneralUserMapper.xml, src/main/webapp/WEB-INF/views/generaluser/generalmypage.jsp
=> 마이페이지 완료(스크랩 제외) - 김철

src/main/java/com/laonworks502/team1st/controller/board/BoardController.java, src/main/java/com/laonworks502/team1st/model/post/PostBean.java, src/main/resources/static/mapper/board/BoardMapper.xml, src/main/webapp/WEB-INF/views/board/boardlist.jsp
board 출력값 변경 (작성자 명이 출력되도록) 수정
=> board 출력값 변경 (작성자 명이 출력되도록) 수정

src/main/java/com/laonworks502/team1st/controller/board/BoardController.java, src/main/java/com/laonworks502/team1st/controller/scrap/ScrapController.java, src/main/java/com/laonworks502/team1st/dao/board/BoardDao.java, src/main/java/com/laonworks502/team1st/dao/scrap/ScrapDao.java, src/main/java/com/laonworks502/team1st/model/post/PostListBean.java, src/main/java/com/laonworks502/team1st/service/board/BoardService.java, src/main/java/com/laonworks502/team1st/service/board/BoardServiceImpl.java, src/main/java/com/laonworks502/team1st/service/scrap/ScrapService.java, src/main/java/com/laonworks502/team1st/service/scrap/ScrapServiceImpl.java, src/main/resources/static/mapper/board/BoardMapper.xml, src/main/resources/static/mapper/scrap/ScrapMapper.xml, src/main/webapp/WEB-INF/views/board/boardlist.jsp, src/main/webapp/WEB-INF/views/board/postview.jsp
=> 민하 : 가짜 ajax

src/main/java/com/laonworks502/team1st/controller/board/BoardController.java, src/main/webapp/WEB-INF/views/board/postview.jsp, src/main/webapp/WEB-INF/views/common/header.jsp
header 수정, controller session 처리 수정 - 미강
=> header 수정, controller session 처리 수정 - 미강

src/main/java/com/laonworks502/team1st/controller/users/CheckApplyController.java, src/main/java/com/laonworks502/team1st/dao/users/CheckApplyDao.java, src/main/java/com/laonworks502/team1st/model/applicant/ApplicantBean.java, src/main/java/com/laonworks502/team1st/service/board/ApplicantServiceImpl.java, src/main/java/com/laonworks502/team1st/service/users/CheckApplyService.java, src/main/java/com/laonworks502/team1st/service/users/CheckApplyServiceImpl.java, src/main/resources/static/mapper/users/CheckApplyMapper.xml, src/main/webapp/WEB-INF/views/companyuser/applicants-list.jsp, src/main/webapp/WEB-INF/views/generaluser/applies-list.jsp
지원자 목록, 지원 내역 목록 , 지원 취소, 이력서 다운로드 구현
=> 지원자 목록, 지원 내역 목록 , 지원 취소, 이력서 다운로드 구현

src/main/java/com/laonworks502/team1st/controller/scrap/ScrapController.java, src/main/java/com/laonworks502/team1st/controller/users/GeneralUserController.java, src/main/java/com/laonworks502/team1st/controller/users/LoginController.java, src/main/webapp/WEB-INF/views/board/boardlist.jsp, src/main/webapp/WEB-INF/views/board/postview.jsp, src/main/webapp/WEB-INF/views/common/header.jsp, src/main/webapp/WEB-INF/views/generaluser/generalmypage.jsp, src/main/webapp/WEB-INF/views/generaluser/totalscrap.jsp
=> 민하 : 스크랩 반대로 된 것 수정

src/main/java/com/laonworks502/team1st/controller/users/CheckApplyController.java, src/main/java/com/laonworks502/team1st/dao/users/CheckApplyDao.java, src/main/java/com/laonworks502/team1st/service/users/CheckApplyService.java, src/main/java/com/laonworks502/team1st/service/users/CheckApplyServiceImpl.java, src/main/resources/static/mapper/users/CheckApplyMapper.xml, src/main/webapp/WEB-INF/views/companyuser/companymypage.jsp, src/main/webapp/WEB-INF/views/generaluser/applies-list.jsp, src/main/webapp/WEB-INF/views/generaluser/generalmypage.jsp
=> 일반 회원 이력서 확인 구현 완료

src/main/webapp/WEB-INF/views/board/boardlist.jsp, src/main/webapp/WEB-INF/views/board/postview.jsp, src/main/webapp/WEB-INF/views/generaluser/applies-list.jsp
=> 날짜 출력 형식 수정

src/main/java/com/laonworks502/team1st/controller/users/GeneralUserController.java, src/main/java/com/laonworks502/team1st/controller/users/LoginController.java, src/main/java/com/laonworks502/team1st/dao/users/GeneralUserDao.java, src/main/java/com/laonworks502/team1st/service/users/GeneralUserServiceImpl.java, src/main/resources/static/mapper/users/GeneralUserMapper.xml, src/main/webapp/WEB-INF/views/generaluser/generalmyboardlist.jsp, src/main/webapp/WEB-INF/views/generaluser/generalmypage.jsp, src/main/webapp/WEB-INF/views/generaluser/generaluserdelete.jsp, src/main/webapp/WEB-INF/views/generaluser/generaluseredit.jsp, src/main/webapp/WEB-INF/views/generaluser/generaluserinsert.jsp, src/main/webapp/WEB-INF/views/generaluser/loginForm.jsp, src/main/webapp/WEB-INF/views/generaluser/loginResult.jsp, src/main/webapp/WEB-INF/views/generaluser/loginselect.jsp, src/main/webapp/WEB-INF/views/generaluser/mainMypage.jsp
mapper파일 '*'제거, 매핑주소 '-'로 구분 등등 세부조정 - 김철,
회원가입 일원화 완료 - 김철
=> 회원가입 일원화 완료 - 김철

src/main/java/com/laonworks502/team1st/controller/board/BoardController.java, src/main/java/com/laonworks502/team1st/controller/studygroup/StudyGroupController.java, src/main/java/com/laonworks502/team1st/dao/board/BoardDao.java, src/main/java/com/laonworks502/team1st/dao/studygroup/StudyGroupDao.java, src/main/java/com/laonworks502/team1st/model/studygroup/StudyGroupBean.java, src/main/java/com/laonworks502/team1st/service/board/BoardService.java, src/main/java/com/laonworks502/team1st/service/board/BoardServiceImpl.java, src/main/java/com/laonworks502/team1st/service/studygroup/StudyGroupService.java, src/main/java/com/laonworks502/team1st/service/studygroup/StudyGroupServiceImpl.java, src/main/resources/static/mapper/board/BoardMapper.xml, src/main/resources/static/mapper/study/StudyMapper.xml, src/main/webapp/WEB-INF/views/board/boardlist.jsp, src/main/webapp/WEB-INF/views/board/posteditform.jsp, src/main/webapp/WEB-INF/views/board/postview.jsp, src/main/webapp/WEB-INF/views/board/postwrite.jsp, src/main/webapp/WEB-INF/views/board/studypostwrite.jsp
=> 매칭 등록, 참여 구현중 - 미강 1220

src/main/java/com/laonworks502/team1st/controller/board/BoardController.java, src/main/webapp/WEB-INF/views/board/postview.jsp
=> 민하 : 스크랩 상세 페이지 오류 수정

src/main/webapp/WEB-INF/views/generaluser/applies-list.jsp, src/main/webapp/WEB-INF/views/index.jsp
=> confirm 변수명 수정

src/main/resources/static/css/decomypage.css, src/main/resources/static/css/decototalscrap.css, src/main/webapp/WEB-INF/views/generaluser/generalmypage.jsp, src/main/webapp/WEB-INF/views/generaluser/totalscrap.jsp
=> 민하 : CSS 수정

src/main/java/com/laonworks502/team1st/controller/studygroup/StudyGroupController.java, src/main/java/com/laonworks502/team1st/dao/studygroup/StudyGroupDao.java, src/main/java/com/laonworks502/team1st/model/studygroup/StudyListBean.java, src/main/java/com/laonworks502/team1st/service/studygroup/StudyGroupService.java, src/main/java/com/laonworks502/team1st/service/studygroup/StudyGroupServiceImpl.java, src/main/resources/static/js/boardcheck.js, src/main/resources/static/mapper/study/StudyMapper.xml, src/main/webapp/WEB-INF/views/board/boardlist.jsp, src/main/webapp/WEB-INF/views/board/posteditform.jsp, src/main/webapp/WEB-INF/views/board/postview.jsp, src/main/webapp/WEB-INF/views/board/postwrite.jsp, src/main/webapp/WEB-INF/views/generaluser/generalmypage.jsp, src/main/webapp/WEB-INF/views/generaluser/studyList.jsp
오류 수정 / 매칭 확인, 취소 구현 완료 - 미강 1222
=> 오류 수정 / 매칭 확인, 취소 구현 완료 - 미강 1222

src/main/java/com/laonworks502/team1st/controller/users/GeneralUserController.java, src/main/resources/static/js/checkgeneral.js, src/main/webapp/WEB-INF/views/generaluser/generalmypage.jsp, src/main/webapp/WEB-INF/views/generaluser/generaluseredit.jsp, src/main/webapp/WEB-INF/views/generaluser/loginResult.jsp
=> 파일 업로드 수정 - 김철

src/main/java/com/laonworks502/team1st/controller/scrap/ScrapController.java, src/main/java/com/laonworks502/team1st/controller/studygroup/StudyGroupController.java, src/main/webapp/WEB-INF/views/board/boardlist.jsp, src/main/webapp/WEB-INF/views/board/postview.jsp, src/main/webapp/WEB-INF/views/generaluser/generalmypage.jsp, src/main/webapp/WEB-INF/views/generaluser/totalscrap.jsp
민하 : reload 없는 스크랩 ajax
: 페이지네이션 오류 아직 수정 중
=> 민하 : reload 없는 스크랩 ajax

src/main/java/com/laonworks502/team1st/controller/scrap/ScrapController.java, src/main/java/com/laonworks502/team1st/controller/studygroup/StudyGroupController.java, src/main/resources/static/mapper/scrap/ScrapMapper.xml, src/main/webapp/WEB-INF/views/generaluser/totalscrap.jsp
=> 민하 : 전체 스크랩 페이지네이션 오류 수정 완료
